using System.Collections.Generic;
using System.Text;

namespace NSS.Blast.Compiler
{
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'HPCNamespace'
    public static class HPCNamespace
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'HPCNamespace'
    {
        static string[] usings = new string[]
        {
            "System",
            "Unity.Burst",
            "Unity.Collections",
            "Unity.Collections.LowLevel.Unsafe",
            "Unity.Jobs",
        };
        static string ns = @"//***********************************************************************************************/
//* generated by <BLAST SCRIPT ENGINE> do not modify ********************************************/                 
//***********************************************************************************************/
{0}

namespace NSS.Blast.Cache
{{

    {1}

}}";

#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member 'HPCNamespace.CombineScriptsIntoNamespace(IEnumerable<string>)'
        static public string CombineScriptsIntoNamespace(IEnumerable<string> scripts)
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member 'HPCNamespace.CombineScriptsIntoNamespace(IEnumerable<string>)'
        {
            StringBuilder sb_using = new StringBuilder();
            foreach (string u in usings)
            {
                sb_using.AppendLine($"using {u};");
            }

            StringBuilder sb_code = new StringBuilder();
            foreach (string s in scripts)
            {
                sb_code.AppendLine("");
                sb_code.AppendLine(s);
            }

            return string.Format(ns, sb_using, sb_code.ToString());
        }

    }
}