//############################################################################################################################
//                                                                                                                           #
//  ██████╗ ██╗      █████╗ ███████╗████████╗                           Copyright © 2022 Rob Lemmens | NijnStein Software    #
//  ██╔══██╗██║     ██╔══██╗██╔════╝╚══██╔══╝                                    <rob.lemmens.s31 gmail com>                 #
//  ██████╔╝██║     ███████║███████╗   ██║                                                                                   #
//  ██╔══██╗██║     ██╔══██║╚════██║   ██║                                                                                   #
//  ██████╔╝███████╗██║  ██║███████║   ██║     V1.0.4e                                                                       #
//  ╚═════╝ ╚══════╝╚═╝  ╚═╝╚══════╝   ╚═╝                                                                                   #
//                                                                                                                           #
//############################################################################################################################ 
#pragma warning disable CS1591
#pragma warning disable CS0162

//
// Warning: spaghetti ahead 
//

#if UNITY_EDITOR || STANDALONE_VSBUILD

using System;
using System.Collections.Generic;
using System.Text;

namespace NSS.Blast.Compiler.CodeGen
{
    static public class CG_ExternalFunctionSupport
    {
        public static string BlastSolutionFileName = "G:\\Repo\\Nijnstein\\BLAST V1\\Assets\\BLAST\\BLAST\\Source\\Interpretor\\codegen\\cg_ef_support.cs"; 
        static string AdditionalNamespaceName = ".External"; 


        static string[] Usings = new string[]
        {
            "System",
            "System.Runtime.CompilerServices",
            "System.Runtime.InteropServices",
            "Unity.Burst",
            "Unity.Mathematics"
        };

        public static string LicenseHeader = @"//###########################################################################################################################
// BLAST v1.0.4c - Copyright © 2022 Rob Lemmens | NijnStein Software <rob.lemmens.s31 gmail com> All Rights Reserved   ^__^\#
// Unauthorized copying of this file, via any medium is strictly prohibited proprietary and confidential               (oo)\#
//                                                                                                                     (__) #
//###########################################################################################################################";

         static string GenerationHeader = @"{0}

// *** This file has been generated by BLAST: modification is futile an will be assimilated ***

#if STANDALONE_VSBUILD
    using NSS.Blast.Standalone;
#else
    using UnityEngine;
    using Unity.Burst.CompilerServices;
#endif

{1}
     
#pragma warning disable CS1591

namespace NSS.Blast{2}
{{

    #region External Function Delegates
    {3}
    #endregion 

}}

namespace NSS.Blast
{{
    #region ScriptAPI registrations and function delegate enumeration
    
    public abstract partial class BlastScriptAPI
    {{
        {8}
    }}

    public enum EFDelegateType : byte
    {{
        {9}
    }}

    #endregion 
}}

namespace NSS.Blast.Interpretor
{{
    #region External Function Calls 

    unsafe public partial struct BlastInterpretor
    {{
        {5}

        {4}
    }}   

    #endregion 

}}

namespace NSS.Blast.SSMD
{{
    #region SSMD External Function Calls 

    unsafe public partial struct BlastSSMDInterpretor
    {{
        {7}

        {6}
    }}

    #endregion

}}

#pragma warning restore CS1591
";


        static string[] types = new string[]
        {
            "float", "float2", "float3", "float4", 
            "Bool32",
            "int", "int2", "int3", "int4"//, "half2", "half4"
        };

        static string[] shorts = new string[]
        {
            "f1", "f2", "f3", "f4",
            "b", 
            "i1", "i2", "i3", "i4"
        };

        static int[] sizes = new int[]
        {
            1, 2, 3, 4, 
            1,
            1, 2, 3, 4
        };


        static string CreateNamespace(string delegate_definitions, string normal_delegate_calls, string normal_call, string ssmd_delegate_calls, string ssmd_call, string api_registrations, string enums)
        {
            StringBuilder s = new StringBuilder();
            foreach(string u in Usings)
            {
                s.AppendLine($"using {u};"); 
            }
            return string.Format(
                GenerationHeader, 
                LicenseHeader, 
                s.ToString(), 
                AdditionalNamespaceName, 
                delegate_definitions,
                normal_delegate_calls,
                normal_call,
                ssmd_delegate_calls,
                ssmd_call, 
                api_registrations, 
                enums); 
        }


        /// <summary>
        /// run codegen to generate all parts need for fluent handling of external functions  
        /// </summary>
        static public string RunExternalFunctionDelegateCodeGen(BlastScriptAPI api)
        {
            StringBuilder delegates = new StringBuilder();
            StringBuilder calls = new StringBuilder();
            StringBuilder ssmd_calls = new StringBuilder();

            // create delegate definitions 
            foreach (ExternalFunctionProfile profile in api.ExternalFunctionProfiles)
            {
                delegates.Append(CreateDelegate(profile));
                if (profile.IsSSMD)
                {
                    ssmd_calls.Append(CreateDelegateCall(profile));
                }
                else
                {
                    calls.Append(CreateDelegateCall(profile));
                }
            }

            // create switch to call the efs
            string normal_call = CreateSwitch(api.ExternalFunctionProfiles, false);
            string ssmd_call = CreateSwitch(api.ExternalFunctionProfiles, true);

            string apiregs = CreateRegisterFunction(api.ExternalFunctionProfiles);
            string enums = CreateEnumeration(api.ExternalFunctionProfiles); 


            // create the cs file  
            return CreateNamespace(delegates.ToString(), calls.ToString(), normal_call, ssmd_calls.ToString(), ssmd_call, apiregs, enums);
        }


        static string CreateSwitch(List<ExternalFunctionProfile> profiles, bool ssmd)
        {
            StringBuilder s = new StringBuilder();

            string returntype = ssmd ? "void*" : "float4";
            string ssmd_count = ssmd ? ", int ssmd_datacount, void* temp" : "";

            s.AppendLine($"internal {returntype} CALL_EF(ref int code_pointer, in BlastScriptFunction function{ssmd_count})");
            s.AppendLine("{");
            s.AppendLine("    int id = function.FunctionId;");
            s.AppendLine("    byte delegate_type = function.FunctionDelegateId;");
            s.AppendLine("");
            if (!ssmd)
            {
                s.AppendLine("    float4 f4;");         // for returning vector types in non ssmd   
                s.AppendLine("    void* temp = &f4; ");
                s.AppendLine("");
            }
            s.AppendLine("    switch(delegate_type)");
            s.AppendLine("    {");

            foreach(ExternalFunctionProfile profile in profiles)
            {
                if(profile.IsSSMD == ssmd)
                {
                    // generate name of function 
                    string functionname = GetCallFunctionName(profile);
                    string ssmd_param = profile.ParameterCount > 0 ? ", ssmd_datacount" : "";

                    // add case for profile and call delegate caller 
                    if (ssmd)
                    {
                        switch (profile.ReturnParameter)
                        {
                            case BlastVectorSizes.none:
                                s.AppendLine($"        case {profile.DelegateType}: {functionname}(ref code_pointer, id{ssmd_param}); return null;");
                                break;
                            case BlastVectorSizes.id1:
                                s.AppendLine($"        case {profile.DelegateType}: return {functionname}(ref code_pointer, id{ssmd_param}, (int*)temp); ");
                                break;                            
                            case BlastVectorSizes.float1:
                                s.AppendLine($"        case {profile.DelegateType}: return {functionname}(ref code_pointer, id{ssmd_param}, (float*)temp); ");
                                break;
                            case BlastVectorSizes.bool32:
                                s.AppendLine($"        case {profile.DelegateType}: return {functionname}(ref code_pointer, id{ssmd_param}, (Bool32*)temp); ");
                                break;
                            case BlastVectorSizes.id2:
                                s.AppendLine($"        case {profile.DelegateType}: return {functionname}(ref code_pointer, id{ssmd_param}, (int2*)temp);");
                                break;                                   
                            case BlastVectorSizes.float2:
                                s.AppendLine($"        case {profile.DelegateType}: return {functionname}(ref code_pointer, id{ssmd_param}, (float2*)temp);");
                                break;
                            case BlastVectorSizes.id3:
                                s.AppendLine($"        case {profile.DelegateType}: return {functionname}(ref code_pointer, id{ssmd_param}, (int3*)temp); ");
                                break;
                            case BlastVectorSizes.float3:
                                s.AppendLine($"        case {profile.DelegateType}: return {functionname}(ref code_pointer, id{ssmd_param}, (float3*)temp); ");
                                break;
                            case BlastVectorSizes.id4:
                                s.AppendLine($"        case {profile.DelegateType}: return {functionname}(ref code_pointer, id{ssmd_param}, (int4*)temp); ");
                                break;
                            case BlastVectorSizes.float4:
                                s.AppendLine($"        case {profile.DelegateType}: return {functionname}(ref code_pointer, id{ssmd_param}, (float4*)temp); ");
                                break;
                        }
                    }
                    else
                    {
                        switch (profile.ReturnParameter)
                        {
                            case BlastVectorSizes.none:
                                s.AppendLine($"        case {profile.DelegateType}: {functionname}(ref code_pointer, id); return 0;");
                                break;
                            case BlastVectorSizes.bool32:
                                // bool is a struct but should pass as float32 as value 
                                s.AppendLine($"        case {profile.DelegateType}: return new float4({functionname}(ref code_pointer, id, (Bool32*)temp)[0].Single, 0, 0, 0);");//.Single; ");
                                break;
                            case BlastVectorSizes.id2:
                                s.AppendLine($"        case {profile.DelegateType}: return new float4({functionname}(ref code_pointer, id, (int2*)temp)[0], 0, 0);");
                                break;
                            case BlastVectorSizes.float2:
                                s.AppendLine($"        case {profile.DelegateType}: return new float4({functionname}(ref code_pointer, id, (float2*)temp)[0], 0, 0);");
                                break;
                            case BlastVectorSizes.id3:
                                s.AppendLine($"        case {profile.DelegateType}: return new float4({functionname}(ref code_pointer, id, (int3*)temp)[0], 0); ");
                                break;
                            case BlastVectorSizes.float3:
                                s.AppendLine($"        case {profile.DelegateType}: return new float4({functionname}(ref code_pointer, id, (float3*)temp)[0], 0); ");
                                break;
                            case BlastVectorSizes.id1:
                            case BlastVectorSizes.float1:
                                s.AppendLine($"        case {profile.DelegateType}: return {functionname}(ref code_pointer, id); ");
                                break;
                            case BlastVectorSizes.id4:
                                s.AppendLine($"        case {profile.DelegateType}: return {functionname}(ref code_pointer, id, (int4*)temp)[0]; ");
                                break;
                            case BlastVectorSizes.float4:
                                s.AppendLine($"        case {profile.DelegateType}: return {functionname}(ref code_pointer, id, (float4*)temp)[0]; ");
                                break;
                        }
                    }
                }
            }

            s.AppendLine("    }");
            s.AppendLine("");
            if (ssmd)
            {
                s.AppendLine("    return null;");
            }
            else
            {
                s.AppendLine("    return float.NaN;");
            }
            s.AppendLine("}");


            return s.ToString(); 
        }

        static string CreateEnumeration(List<ExternalFunctionProfile> profiles)
        {
            StringBuilder sb = new StringBuilder();
            foreach(ExternalFunctionProfile profile in profiles)
            {
                sb.AppendLine(CreateEnumeration(profile)); 
            }

            return sb.ToString(); 
        }

        static string CreateEnumeration(ExternalFunctionProfile profile)
        {
            return $"{GetCallFunctionName(profile)} = {profile.DelegateType},"; 
        }

        static string CreateRegisterFunction(List<ExternalFunctionProfile> profiles)
        {
            StringBuilder sb = new StringBuilder();
            foreach (ExternalFunctionProfile profile in profiles)
            {
                sb.AppendLine(CreateRegisterFunction(profile));
            }

            return sb.ToString();
        }
        static string CreateRegisterFunction(ExternalFunctionProfile profile)
        {
            string parameters = "";
            string postfix = "";
            string delegate_name = "";

            GetDelegateParameterInfo(profile, ref parameters, ref postfix, ref delegate_name);
            string shortname = profile.IsShortDefinition ? "_SHORT" : "";
            string returns = profile.ReturnsValue ? "_" + profile.ReturnParameter.ShortTypeName().ToUpper() : "";
            string ssmd = profile.IsSSMD ? "_SSMD" : "";

            string function_name = $"CALL_PROC_EF{shortname}{ssmd}{returns}{postfix}";
            string isshort = profile.IsShortDefinition ? "true" : "false";

            string enumname = "EFDelegateType." + function_name;

            return $"public int Register(External.{delegate_name} function, string name = null) {{ return RegisterFunction(function, name, {profile.ParameterCount}, {isshort}, (byte){enumname}); }}"; 
        }


        static string GetCallFunctionName(ExternalFunctionProfile profile)
        {
            string parameters = "";
            string postfix = "";
            string delegate_name = "";

            GetDelegateParameterInfo(profile, ref parameters, ref postfix, ref delegate_name);

            string shortname = profile.IsShortDefinition ? "_SHORT" : "";
            string returns = profile.ReturnsValue ? "_" + profile.ReturnParameter.ShortTypeName().ToUpper() : "";
            string ssmd = profile.IsSSMD ? "_SSMD" : "";

            return $"CALL_PROC_EF{shortname}{ssmd}{returns}{postfix}";
        }



        // any function using float 2-4 or any other struct should pass it as pointer


        static string CreateDelegateCall(ExternalFunctionProfile profile)
        {
            StringBuilder s = StringBuilderCache.Acquire();

            string parameters = "";
            string postfix = "";
            string delegate_name = ""; 

            GetDelegateParameterInfo(profile, ref parameters, ref postfix, ref delegate_name);

            string shortname = profile.IsShortDefinition ? "_SHORT" : ""; 
            string returns = profile.ReturnsValue ? "_" + profile.ReturnParameter.ShortTypeName().ToUpper() : "";
            string ssmd = profile.IsSSMD ? "_SSMD" : "";
            string ptr = profile.IsSSMD ? "*" : "";

            string ssmd_count = profile.IsSSMD && profile.ParameterCount > 0 ? ", int ssmd_datacount" : "";
            string ssmd_param = profile.IsSSMD && profile.ParameterCount > 0 ? ", ssmd_datacount" : "";

            
            bool result_needs_pointer = profile.ReturnParameter.VectorSize() > 1 || profile.ReturnParameter == BlastVectorSizes.bool32;


            // if ssmd or vector return : pointer
            string returns_ptr = profile.ReturnsValue ? (result_needs_pointer ? "*" : ptr) : "";
            string ssmd_return_buffer = (profile.IsSSMD || result_needs_pointer) && profile.ReturnsValue ? $", {profile.ReturnParameter.FullTypeName()}{returns_ptr} result" : "";

            // if there are parameters dont inline the function 
            if (profile.IsSSMD && profile.ParameterCount > 0)
            {
                // dont zero memory of buffers
                s.AppendLine("#if !STANDALONE_VSBUILD");
                s.AppendLine("   [Unity.Burst.CompilerServices.SkipLocalsInit]");
                s.AppendLine("#endif");

                // dont inline stackallocs they are unconditional
                s.AppendLine("[MethodImpl(MethodImplOptions.NoInlining)]");
            }
            else
            {
                // if no allocations needed,
                s.AppendLine("[MethodImpl(MethodImplOptions.AggressiveInlining)]");
            }

            s.AppendLine($"internal {profile.ReturnParameter.FullTypeName()}{returns_ptr} CALL_PROC_EF{shortname}{ssmd}{returns}{postfix}(ref int code_pointer, in int function_id{ssmd_count}{ssmd_return_buffer})");
            s.AppendLine("{");

            string delegate_parameters = ""; 
            if (profile.ParameterCount > 0)
            {
                // these are only needed if we have params 
                if (!profile.IsSSMD)
                {
                    s.AppendLine("   byte vector_size;");
                    s.AppendLine("   bool is_negated;");
                    s.AppendLine("   BlastVariableDataType vtype;");
                }
                if (!profile.IsSSMD) s.AppendLine($"  void* vdata;");

                // pop each parameter
                for(int  i = 0; i < profile.ParameterCount; i++)
                {
                    if (profile.IsSSMD)
                    {
                        string parametertype;
                        if (profile.ParameterType(i) == BlastVectorSizes.bool32)
                        {
                            parametertype = "float";
                        }
                        else
                        {
                            parametertype = profile.ParameterType(i).FullTypeName();
                        }
                        s.AppendLine($"   {parametertype}* p{(i + 1)} = stackalloc {parametertype}[ssmd_datacount];");
                        s.AppendLine($"   pop_fx_into_ref<{parametertype}>(ref code_pointer, p{(i + 1)});");
                    }
                    else
                    {
                        s.AppendLine($"   vdata = (void*)pop_p_info(ref code_pointer, out vtype, out vector_size, out is_negated);");
                        s.AppendLine("#if TRACE");
                        s.AppendLine($"   if (vector_size != {profile.ParameterType(i).VectorSize()}) goto CALLERROR;");
                        s.AppendLine("#endif");

                        switch (profile.ParameterType(i))
                        {
                            case BlastVectorSizes.float1: s.AppendLine($"   float p{(i + 1)} = math.select(((float*)vdata)[0], -((float*)vdata)[0], is_negated);"); break;
                            case BlastVectorSizes.float2: s.AppendLine($"   float2 p{(i + 1)} = math.select(((float2*)vdata)[0], -((float2*)vdata)[0], is_negated);"); break;
                            case BlastVectorSizes.float3: s.AppendLine($"   float3 p{(i + 1)} = math.select(((float3*)vdata)[0], -((float3*)vdata)[0], is_negated);"); break;
                            case BlastVectorSizes.float4: s.AppendLine($"   float4 p{(i + 1)} = math.select(((float4*)vdata)[0], -((float4*)vdata)[0], is_negated);"); break;
                            case BlastVectorSizes.id1:    s.AppendLine($"   int p{(i + 1)} = ((int*)vdata)[0]; p{(i + 1)} = math.select(p{(i + 1)}, -p{(i + 1)}, is_negated);"); break;
                            case BlastVectorSizes.id2:    s.AppendLine($"   int2 p{(i + 1)} = ((int2*)vdata)[0]; p{(i + 1)} = math.select(p{(i + 1)}, -p{(i + 1)}, is_negated);"); break;
                            case BlastVectorSizes.id3:    s.AppendLine($"   int3 p{(i + 1)} = ((int3*)vdata)[0]; p{(i + 1)} = math.select(p{(i + 1)}, -p{(i + 1)}, is_negated);"); break;
                            case BlastVectorSizes.id4:    s.AppendLine($"   int4 p{(i + 1)} = ((int4*)vdata)[0]; p{(i + 1)} = math.select(p{(i + 1)}, -p{(i + 1)}, is_negated);"); break;
                            case BlastVectorSizes.bool32: s.AppendLine($"   Bool32 p{(i + 1)} = Bool32.From(math.select(((Bool32*)vdata)[0].Unsigned, ~((Bool32*)vdata)[0].Unsigned, is_negated));"); break;
                        }
                    }
                    if (i > 0) delegate_parameters += ", ";
                    if (profile.ParameterType(i) == BlastVectorSizes.bool32 && profile.IsSSMD)
                    {
                        delegate_parameters += $"(Bool32*)(p{(i + 1)})";
                    }
                    else
                    {
                        if (!profile.IsSSMD && (profile.ParameterType(i).VectorSize() > 1 || profile.ParameterType(i) == BlastVectorSizes.bool32))
                        {
                            delegate_parameters += $"&p{(i + 1)}";
                        }
                        else
                        {
                            delegate_parameters += $"p{(i + 1)}";
                        }
                    }
                }
            }

            // result value
            if (!profile.IsSSMD)
            {
                switch (profile.ReturnParameter)
                {
                    case BlastVectorSizes.none: break;
                    case BlastVectorSizes.float1: s.AppendLine($"   float{ptr} result;"); break;
                    case BlastVectorSizes.id1: s.AppendLine($"   int{ptr} result;"); break;
                    case BlastVectorSizes.id64: s.AppendLine($"   long{ptr} result;"); break;
                    case BlastVectorSizes.ptr: s.AppendLine($"   void*{ptr} result;"); break;
                }
            }
            // call external 
            string long_params = profile.IsShortDefinition ? "" : "(IntPtr)engine_ptr, environment_ptr";
            if (!profile.IsShortDefinition && !profile.IsSSMD) long_params += ", caller_ptr";
            if (!profile.IsShortDefinition)
            {
                if (profile.IsSSMD)
                {
                    if (profile.ReturnsValue || profile.ParameterCount > 0) long_params += ", ";
                }
                else
                {
                    if (
                    !string.IsNullOrWhiteSpace(delegate_parameters)
                    ||
                    profile.ReturnParameter.VectorSize() > 1
                    ||
                    profile.ReturnParameter == BlastVectorSizes.bool32) long_params += ", ";
                }
            }


            if (profile.ParameterCount > 0 || !profile.IsShortDefinition)
            {
                if (profile.IsSSMD && (profile.ReturnsValue || profile.ParameterCount > 0)) ssmd_param = ", ssmd_datacount"; else ssmd_param = "";
            }
            else
            {
                if (profile.IsSSMD && (profile.ReturnsValue || profile.ParameterCount > 0)) ssmd_param = "ssmd_datacount"; else ssmd_param = "";
            }


            s.AppendLine("#if STANDALONE_VSBUILD");
            if (profile.ReturnsValue)
            {
                string passbuffer = profile.IsSSMD || result_needs_pointer ? (profile.ParameterCount > 0 ? "result, " : "result"): "";
                s.AppendLine($"   result = (Blast.Instance.API.FunctionInfo[function_id].FunctionDelegate as External.{delegate_name}).Invoke({long_params}{passbuffer}{delegate_parameters}{ssmd_param});");
                s.AppendLine("   return result;");
            }
            else
            {
                s.AppendLine($"  (Blast.Instance.API.FunctionInfo[function_id].FunctionDelegate as External.{delegate_name}).Invoke({long_params}{delegate_parameters}{ssmd_param});");
                s.AppendLine("   return;");
            }
            

            s.AppendLine("#else");

            // burstcompatible native function pointer call 
            s.AppendLine($"   FunctionPointer<External.{delegate_name}> fp = engine_ptr->Functions[function_id].Generic<External.{delegate_name}>();");
            s.AppendLine("    if (fp.IsCreated && fp.Value != IntPtr.Zero)");
            s.AppendLine("    {");

            if (profile.ReturnsValue)
            {
                string passbuffer = profile.IsSSMD || result_needs_pointer ? (profile.ParameterCount > 0 ? "result, " : "result") : "";
                s.AppendLine($"       result = fp.Invoke({long_params}{passbuffer}{delegate_parameters}{ssmd_param});");
                s.AppendLine("       return result;");
            }
            else
            {
                s.AppendLine($"       fp.Invoke({long_params}{delegate_parameters}{ssmd_param});");
                s.AppendLine("       return;");
            }
            s.AppendLine("    }");

            s.AppendLine("#endif");            


            // error catch|log
            if(profile.ParameterCount > 0 && !profile.IsSSMD) s.AppendLine("CALLERROR:");
            s.AppendLine("#if TRACE");
            s.AppendLine($"    Debug.LogError($\"Blast.interpretor.{delegate_name}: error calling external function with id {{function_id}}\");");
            s.AppendLine("#endif");

            // return return error value
            if (profile.IsSSMD)
            {
                switch (profile.ReturnParameter)
                {
                    case BlastVectorSizes.none: s.AppendLine("   return;"); break;
                    default: s.AppendLine("   return null;"); break;
                }
            }
            else
            {
                switch (profile.ReturnParameter)
                {
                    case BlastVectorSizes.none: s.AppendLine("   return;"); break;
                    case BlastVectorSizes.float1: s.AppendLine("   return float.NaN;"); break;
                    case BlastVectorSizes.float2:
                    case BlastVectorSizes.float3:
                    case BlastVectorSizes.float4: 
                    case BlastVectorSizes.bool32: s.AppendLine("   return null;"); break;
                    case BlastVectorSizes.id1: s.AppendLine("   return 0;"); break;
                    case BlastVectorSizes.id2:
                    case BlastVectorSizes.id3:
                    case BlastVectorSizes.id4: 
                    case BlastVectorSizes.id64: s.AppendLine("   return null;"); break;
                    case BlastVectorSizes.half2:
                    case BlastVectorSizes.half4: s.AppendLine("   return null;"); break;
                    case BlastVectorSizes.ptr: s.AppendLine("   return null;"); break;
                }
            }  
            // done            
            s.AppendLine("}");

            return StringBuilderCache.GetStringAndRelease(ref s);
        }

        static string CreateDelegate(ExternalFunctionProfile profile)
        {
            StringBuilder code = StringBuilderCache.Acquire();

            string returntype = profile.ReturnParameter.FullTypeName();
            string returntype_short = profile.ReturnParameter.ShortTypeName();


            string parameters = "";
            string postfix = "";
            string delegate_name = "";

            GetDelegateParameterInfo(profile, ref parameters, ref postfix, ref delegate_name);

            code.Append("[UnmanagedFunctionPointer(CallingConvention.Cdecl)] ");

            if (profile.IsShortDefinition)
            {
                if (profile.ReturnsValue && (profile.ReturnParameter.VectorSize() > 1 || profile.ReturnParameter == BlastVectorSizes.bool32))
                {
                    code.Append($"unsafe public delegate {returntype}* {delegate_name}([NoAlias]{returntype}* result");
                    if (profile.ParameterCount > 0) code.Append(", ");
                }
                else
                {
                    code.Append($"unsafe public delegate {returntype} {delegate_name}(");
                }
            }
            else
            if (profile.IsSSMD)
            {
                if (profile.ReturnsValue)
                {
                    code.Append($"unsafe public delegate {returntype}* {delegate_name}([NoAlias]IntPtr engine, [NoAlias]IntPtr data, [NoAlias]{returntype}* result");
                }
                else
                {
                    code.Append($"unsafe public delegate {returntype}* {delegate_name}([NoAlias]IntPtr engine, [NoAlias]IntPtr data");
                }
            }
            else
            {
                if (profile.ReturnsValue && (profile.ReturnParameter.VectorSize() > 1 || profile.ReturnParameter == BlastVectorSizes.bool32))
                {
                    code.Append($"unsafe public delegate {returntype}* {delegate_name}([NoAlias]IntPtr engine, [NoAlias]IntPtr data, [NoAlias]IntPtr caller, [NoAlias]{returntype}* result");
                }
                else
                {
                    code.Append($"unsafe public delegate {returntype} {delegate_name}([NoAlias]IntPtr engine, [NoAlias]IntPtr data, [NoAlias]IntPtr caller");
                }                                                                                                                                                                                
            }

            code.Append(parameters);
            code.AppendLine(");");

            return StringBuilderCache.GetStringAndRelease(ref code);
        }

        static void GetDelegateParameterInfo(ExternalFunctionProfile profile, ref string parameters, ref string postfix, ref string delegate_name)
        {
            if (profile.ParameterCount > 0)
            {
                for (int i = 0; i < profile.ParameterCount; i++)
                {
                    BlastVectorSizes psize = profile.ParameterType(i);
                    if (i >= 1 || !profile.IsShortDefinition)
                    {
                        parameters += ", ";
                    }

                    if (!profile.IsSSMD)
                    {
                        if (profile.ParameterType(i).VectorSize() > 1 || profile.ParameterType(i) == BlastVectorSizes.bool32)
                        {
                            parameters += $"[NoAlias]{psize.FullTypeName()}* p{i}";
                        }
                        else
                        {
                            parameters += $"{psize.FullTypeName()} p{i}";
                        }
                    }
                    else
                    {
                        parameters += $"[NoAlias]{psize.FullTypeName()}* p{i}";
                    }
                    postfix += psize.ShortTypeName();
                }
            }
            if (!string.IsNullOrWhiteSpace(postfix)) postfix = "_" + postfix;

            if (profile.IsSSMD)
            {
                if (profile.ParameterCount > 0 || profile.ReturnsValue)
                {
                    parameters += ", int ssmd_datacount";
                }
            }

            string returns = profile.ReturnsValue ? "_" + profile.ReturnParameter.ShortTypeName().ToUpper() : "";

            delegate_name = string.Format("{0}{1}Delegate{2}{3}",
                profile.IsShortDefinition ? "BSEF" : "BlastEF",
                profile.IsSSMD ? "SSMD" : "",
                returns,
                postfix);
        }

    }
}


#endif 
