#define result_case_1 2020.2020
#define result_case_2 1010.1010
#define stack_size 0                      # set stack size in bytes, if set to 0 it wil use value from estimator or settings           

aa = 2;

if( aa & (aa - 1) ) 
  then ( aa = 42 ; ab = 42 * 1 * 1 * 1  )
  else ( aa = 2 );  

ab = 1; 

while(aa > (2 - 10))
(
  aa = aa - 1; 
  ab = ab + aa; 
);

switch(ab)
(
  case >= 826:
  (
    ac = result_case_1; 
  )
  case >= -34:
  (
    ac = result_case_2; 
  )
  default:
  (
    ac = -100;
  )
);

#validate aa -8               
#validate ab 826              
#validate ac 2020.2020        