
# a lot of magic happens:
# - tokenizer splits it first as a token and identifier, then it is recombined depending on context
# - parser then splits it again in seperate instructions if the identifier can be found in constants (which are all positive)
#
a = -1; 

# assigning b with something that is not a known systemconstant, the minus should be combined with the identifier 
b = -7238.23;

# compiler node tree
# 
#    root of 2 
#       assignment of a 
#          operation Substract 
#          constant parameter 1 
#       /
#       assignment of b 
#          parameter -7238.23 
#       /
#    /
# 
#
# Note how in the output the assignment of b is 1 codebyte smaller (but does comsume 4 bytes of dataspace)
#    001 128 003 085     000     001 129 130     000 


#validate a -1
#validate b -7238.23

 