using System;
using System.Collections.Generic;
using System.Text;

namespace NSS.Blast.Compiler
{
    public static class CSNamespace
    {
        static string[] usings = new string[]
        {
            "System",
            "Unity.Burst",
            "Unity.Collections",
            "Unity.Collections.LowLevel.Unsafe",
            "Unity.Jobs",
        };

        static string ns = @"/*Generated by Blast*/
{0}

namespace NSS.Blast.Cache.CS
{{
    {1}
}}";

        static public string CombineScriptsIntoNamespace(IEnumerable<string> scripts)
        {
            StringBuilder sb_using = GetUsings();

            StringBuilder sb_code = new StringBuilder();
            foreach (string s in scripts)
            {
                sb_code.AppendLine("");
                sb_code.AppendLine(s);
            }

            return string.Format(ns, sb_using, sb_code.ToString());
        }

        private static StringBuilder GetUsings()
        {
            StringBuilder sb_using = new StringBuilder();
            foreach (string u in usings)
            {
                sb_using.AppendLine($"using {u};");
            }

            return sb_using;
        }

        static public string MergeScriptIntoNamespace(string script)
        {
            return string.Format(ns, GetUsings(), Environment.NewLine + script);
        }

    }
}